# Generated by Django 5.0.4 on 2024-04-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageimages',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
